name: push to swarm

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod
      - name: unzip
        run: |
             unzip democon.zip -d public/ 
             cd public/devcon-vi-2022/devcon-vi-2022
             mv * ../
             cd ${GITHUB_WORKSPACE}
      - name: unzip
        continue-on-error: true
        run: |
             mv public/devcon-vi-2022/media/devcon-vi-2022/* public/devcon-vi-2022/media/
#      - name: replace
#        run: |
#             ls -lsatrh
#             find '*' -type f -exec  sed -i 's#/democon##/g' {} +
      - name: Find and Replace href
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '/devcon-vi-2022/'
          replace: '/'
          include: "**"
          regex: true
  
      - name: Upload
        id: swarm-upload
        uses: ethersphere/swarm-actions/upload-dir@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          dir: ./public/devcon-vi-2022/
          index-document: index.html
          error-document: 404.html
          timeout: 1200000 
      - name: update feed
        id: swarm-feed
        uses: ethersphere/swarm-actions/write-feed@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          reference: ${{ steps.swarm-upload.outputs.reference }}
          topic: devconagenda
          signer: ${{ secrets.SIGNER }}
      - name: get CID
        id: swarm-cid
        uses: ethersphere/swarm-actions/reference-to-cid@latest
        with:
          reference: ${{ steps.swarm-feed.outputs.reference }}
      - name: print
        run: |
          echo "upload ref: " ${{ steps.swarm-upload.outputs.reference }}
          echo "feed ref: " ${{ steps.swarm-feed.outputs.reference }}
          echo "CID: " ${{ steps.swarm-cid.outputs.cid }}
          echo 'Feed Manifest: ${{ steps.swarm-feed.outputs.manifest }}'
      - name: purge cache
        env:
          TOKEN: '${{ secrets.purge_token }}'
        run: |
          curl -s https://fairos.fairdatasociety.org/deploy/purge?token=$TOKEN -H "site: devconagenda.link"
