name: push to swarm

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod
      - name: Upload
        id: swarm-upload
        uses: ethersphere/swarm-actions/upload-dir@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          dir: ./public/
          index-document: index.html
          error-document: 404.html
          timeout: 120000
      - name: update feed
        id: swarm-feed
        uses: ethersphere/swarm-actions/write-feed@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          reference: ${{ steps.swarm-upload.outputs.reference }}
          topic: devconagenda
          signer: ${{ secrets.SIGNER }}
      - name: get CID
        id: swarm-cid
        uses: ethersphere/swarm-actions/reference-to-cid@latest
        with:
          reference: ${{ steps.swarm-feed.outputs.reference }}
      - name: print
        run: |
          echo "upload ref: " ${{ steps.swarm-upload.outputs.reference }}
          echo "feed ref: " ${{ steps.swarm-feed.outputs.reference }}
          echo "CID: " ${{ steps.swarm-cid.outputs.cid }}
          echo 'Feed Manifest: ${{ steps.swarm-feed.outputs.manifest }}'
